### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by acroca** [dolaterio/dolaterio#17]
Use a config file to read various configuration variables. Some of the required config variables on top of my mind are:
- rethink db connection
- redis connection
- api port

**Comment by acroca** [comment]
@jsegura ping

**Comment by acroca** [comment]
@jsegura do you mind if I implement this?

**Comment by jsegura** [comment]
go ahead

On Thu, May 21, 2015 at 5:28 PM, Albert Callarisa <notifications@github.com>
wrote:

> @jsegura <https://github.com/jsegura> do you mind if I implement this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dolaterio/dolaterio/issues/17#issuecomment-104319645>.
>



-- 
Javier
